#!/bin/bash

play clean compile dist
echo "[LOCAL DIST ZIP] Created!"

PEM_FILE='/Users/raul/GitHub/itafy/itafyServer.pem'
SSH='ssh ubuntu@54.213.21.104 -i $PEM_FILE'
DIST_FOLDER='/Users/raul/GitHub/itafy/dist/itafy-0.1.zip'
REMOTE_FOLDER='ubuntu@54.72.212.197:/home/ubuntu'

$SSH "rm itafy-0.1.zip"
echo "[OLD REMOTE DIST ZIP] Deleted or inexistent!"

$SSH "rm -rf itafy-0.1_OLD/"
echo "[OLD REMOTE DIST FOLDER] Deleted or inexistent!"

$SSH "mv itafy-0.1/ itafy-0.1_OLD"

scp -r -i $PEM_FILE $DIST_FOLDER $REMOTE_FOLDER
echo "[REMOTE DIST ZIP] Copied!"

$SSH "unzip itafy-0.1.zip"
echo "[REMOTE DIST ZIP] Unzipped!"

$SSH "cp twitter4j.properties itafy-0.1/"
echo "[TWITTER4J CONFIG FILE] Copied!"
